// schema.mjs — PURE DATA. Declarative Directus collection/field/relation definitions.
// No @directus/sdk imports, no logic. bootstrap.mjs iterates these arrays via its
// ensure* helpers (data-vs-logic split — see 01-PATTERNS.md).
//
// Authoritative spec: 01-01-PLAN.md <interfaces> + PLAN.md §3.
// HARD CONTRACTS encoded here:
//   - DZD = type:"integer" on products.base_price, variants.price, variants.stock (D-01).
//     NO numeric / float / decimal anywhere in this file.
//   - uuid PK on every collection via special:["uuid"] (Directus auto-generates on insert).
//   - FK fields carry special:["m2o"]; relations use the CREATE-body shape
//     { collection, field, related_collection, meta:{ one_field, one_deselect_action:"nullify", sort_field:null } }
//     — NOT collection_many/field_many (that is the GET-response shape). RESEARCH Pattern 4.

// ---------------------------------------------------------------------------
// Field-definition helpers (plain object factories — data, not behaviour).
// ---------------------------------------------------------------------------

// uuid primary key, auto-generated by Directus on insert.
const pk = () => ({
  field: "id",
  type: "uuid",
  schema: { is_primary_key: true, has_auto_increment: false, is_nullable: false },
  meta: { special: ["uuid"], interface: "input", readonly: true, hidden: true },
});

// Foreign-key column (m2o). related PK is uuid → FK column is uuid.
const fk = (field, { nullable = false } = {}) => ({
  field,
  type: "uuid",
  schema: { is_nullable: nullable },
  meta: { special: ["m2o"], interface: "select-dropdown-m2o" },
});

const str = (field, { nullable = true, default_value = undefined } = {}) => ({
  field,
  type: "string",
  schema: {
    is_nullable: nullable,
    ...(default_value !== undefined ? { default_value } : {}),
  },
});

const text = (field, { nullable = true } = {}) => ({
  field,
  type: "text",
  schema: { is_nullable: nullable },
});

// Unique text column used as a natural key (e.g. variants.sku, ads.ad_id).
const uniqueText = (field) => ({
  field,
  type: "text",
  schema: { is_nullable: false, is_unique: true },
});

// integer — whole DZD dinars (D-01). default 0 unless nullable.
const integer = (field, { nullable = false, default_value = 0 } = {}) => ({
  field,
  type: "integer",
  schema: {
    is_nullable: nullable,
    ...(nullable ? {} : { default_value }),
  },
});

const json = (field) => ({
  field,
  type: "json",
  schema: { is_nullable: true },
  meta: { special: ["cast-json"], interface: "input-code" },
});

// boolean flag (e.g. merchants.is_default — the tenant the resolver falls back to).
const bool = (field, { default_value = false } = {}) => ({
  field,
  type: "boolean",
  schema: { is_nullable: true, default_value },
  meta: { special: ["cast-boolean"], interface: "boolean" },
});

const createdAt = () => ({
  field: "created_at",
  type: "timestamp",
  schema: { default_value: "now()", is_nullable: true },
  meta: { special: ["date-created"], interface: "datetime", readonly: true },
});

const updatedAt = () => ({
  field: "updated_at",
  type: "timestamp",
  schema: { is_nullable: true },
  meta: { special: ["date-updated"], interface: "datetime", readonly: true },
});

const timestamp = (field) => ({
  field,
  type: "timestamp",
  schema: { is_nullable: true },
  meta: { interface: "datetime" },
});

// string enum via select-dropdown choices.
const enumField = (field, values, { nullable = true, default_value = undefined } = {}) => ({
  field,
  type: "string",
  schema: {
    is_nullable: nullable,
    ...(default_value !== undefined ? { default_value } : {}),
  },
  meta: {
    interface: "select-dropdown",
    options: {
      choices: values.map((v) => ({ text: v[0].toUpperCase() + v.slice(1), value: v })),
    },
  },
});

// A collection definition: empty schema:{} tells Directus "create the table".
const collection = (name, icon, fields) => ({
  collection: name,
  schema: {},
  meta: { icon, hidden: false },
  fields,
});

// ---------------------------------------------------------------------------
// Collections (7). Order matters at create time: parents before children so
// FK fields reference existing PKs — bootstrap creates collections, then scalar
// fields, then FK fields, then relations (RESEARCH Pitfall 3).
// ---------------------------------------------------------------------------

export const collections = [
  collection("merchants", "store", [
    pk(),
    str("name", { nullable: false }), // natural key
    // --- tenant registry (multi-tenant routing) ---
    json("inbox_ids"), // Chatwoot inbox ids this tenant owns; agent-handler resolveTenant(inbox)→merchant
    bool("is_default"), // the fallback tenant for any unmapped inbox (SIRINE) — keeps the live bot green
    createdAt(),
  ]),

  collection("products", "shopping_bag", [
    pk(),
    fk("merchant_id"),
    str("name", { nullable: false }), // natural key
    enumField("category", ["shoes", "bags", "accessories", "packs", "course"]),
    text("description"),
    // base_price NULLABLE: a NULL price = "on request". A NOT-NULL default-0 would seed those as
    // a false "0 DZD / free" fact (anti-hallucination breach). For EXISTING DBs the NOT-NULL/default
    // is dropped by sql/03-multitenant.sql (ensureField can't alter an existing column).
    integer("base_price", { nullable: true }), // DZD integer or NULL (on request)
    str("currency", { nullable: false, default_value: "DZD" }),
    enumField("status", ["active", "hidden"], { default_value: "active" }),
    text("search_text"), // maintained by pg trigger (plan 02)
    // --- optional descriptive fields (NULL for SIRINE; available for service-type catalogs) ---
    str("duration"), // NULL when unknown (never invented)
    text("certification"),
    text("prerequisites"),
    str("location"), // wilaya(s) / city
    createdAt(),
    updatedAt(),
  ]),

  collection("variants", "style", [
    pk(),
    fk("product_id"),
    fk("merchant_id", { nullable: true }), // denormalized tenant tag (filter without a join)
    str("color"),
    str("size"),
    integer("price", { nullable: true }), // DZD integer, nullable (inherits product base_price)
    integer("stock", { nullable: true }), // integer count, nullable (course seats unknown)
    uniqueText("sku"), // natural key
    createdAt(),
  ]),

  collection("images", "image", [
    pk(),
    fk("product_id"),
    fk("merchant_id", { nullable: true }), // denormalized tenant tag
    fk("variant_id", { nullable: true }),
    text("url", { nullable: false }), // Directus file UUID ref
    enumField("angle", ["front", "back", "side", "detail"]),
    text("ai_description"), // NULL until M5
    json("attributes"), // jsonb, NULL until M5
    timestamp("tagged_at"), // NULL until M5
  ]),

  collection("ads", "campaign", [
    pk(),
    fk("merchant_id"),
    uniqueText("ad_id"), // natural key — AD_TEST_001..003 contract
    enumField("channel", ["whatsapp", "messenger", "instagram"]),
    enumField("status", ["active", "paused", "archived"], { default_value: "active" }),
    str("headline"),
    text("body"),
    json("creative_images"), // jsonb
    fk("linked_product_id", { nullable: true }),
    timestamp("synced_at"),
  ]),

  collection("leads", "person_add", [
    pk(),
    fk("merchant_id"),
    str("name"),
    text("phone"), // E.164-ready
    str("channel"),
    text("source_ad_id"),
    fk("product_id", { nullable: true }),
    text("conversation_id"),
    enumField("status", ["new", "contacted", "confirmed", "lost"], { default_value: "new" }),
    createdAt(),
  ]),

  // Captured orders — written by agent-handler's capture_order tool after the customer
  // confirms. The team works them from the Directus UI (filter on status, export CSV).
  // Money fields are computed SERVER-SIDE (price re-verified against the catalog, shipping
  // from shipping.json) — never trusted from the model.
  collection("orders", "shopping_cart", [
    pk(),
    fk("merchant_id"),
    str("customer_name", { nullable: false }),
    str("phone_e164", { nullable: false }), // validated +213[567]XXXXXXXX
    str("wilaya", { nullable: false }), // canonical French name from shipping.json
    integer("wilaya_code", { nullable: true }), // 1..58
    fk("product_id", { nullable: true }), // resolved catalog product (nullable: survives product deletion)
    str("product_name", { nullable: false }), // denormalized snapshot at order time
    str("variant_color"),
    str("variant_size"),
    integer("qty", { nullable: false, default_value: 1 }),
    enumField("delivery_type", ["home", "desk"], { nullable: false }),
    integer("unit_price_dzd", { nullable: false }), // catalog price at order time (server-verified)
    integer("shipping_dzd", { nullable: false }), // from shipping.json at order time
    integer("total_dzd", { nullable: false }), // unit_price*qty + shipping
    text("address"), // full address (home delivery) / pickup notes (desk)
    text("notes"),
    text("conversation_id"), // Chatwoot conversation for follow-up
    text("source_ad_id"), // Facebook ad that started the conversation (when known)
    text("source_ref"), // Meta ref parameter (when present)
    enumField("status", ["new", "confirmed", "shipped", "delivered", "cancelled"], { default_value: "new" }),
    createdAt(),
    updatedAt(),
  ]),
];

// ---------------------------------------------------------------------------
// Relations (12). CREATE-body shape (RESEARCH Pattern 4):
//   { collection:<many side>, field:<fk>, related_collection:<one side>,
//     meta:{ one_field:<reverse alias|null>, one_deselect_action:"nullify", sort_field:null } }
// The FK field (above, special:["m2o"]) MUST exist before the relation is created.
// ---------------------------------------------------------------------------

const relation = (many, field, one, oneField) => ({
  collection: many,
  field,
  related_collection: one,
  meta: { one_field: oneField, one_deselect_action: "nullify", sort_field: null },
});

export const relations = [
  relation("products", "merchant_id", "merchants", "products"),
  relation("variants", "product_id", "products", "variants"),
  relation("variants", "merchant_id", "merchants", null), // denormalized tag; no reverse alias
  relation("images", "product_id", "products", "images"),
  relation("images", "merchant_id", "merchants", null), // denormalized tag; no reverse alias
  relation("images", "variant_id", "variants", "images"),
  relation("ads", "merchant_id", "merchants", "ads"),
  relation("ads", "linked_product_id", "products", "linked_ads"),
  relation("leads", "merchant_id", "merchants", "leads"),
  relation("leads", "product_id", "products", "leads"),
  relation("orders", "merchant_id", "merchants", "orders"),
  relation("orders", "product_id", "products", "orders"),
];
